# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Open PR to Bazel Registry

on:
  workflow_run:
    workflows: ["Update Bazel Registry"]
    types:
      - completed

jobs:
  open_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Extract Module Name
        id: extract_module
        run: |
          MODULE_NAME=$(awk '/module\s*\(/ {found=1} found && /name\s*=/ {gsub(/"/, "", $0); split($0, a, "="); gsub(/[[:space:]]*/, "", a[2]); print a[2]; exit}' MODULE.bazel)
          if [ -z "$MODULE_NAME" ]; then
            MODULE_NAME=$(basename "$GITHUB_REPOSITORY")
          fi
          echo "module_name=$MODULE_NAME" >> $GITHUB_OUTPUT

      - name: Commit and Push
        run: |
          MODULE_NAME="${{ steps.extract_module.outputs.module_name }}"
          cd bazel_registry_fork
          BRANCH_NAME="update-${MODULE_NAME}-${GITHUB_REF_NAME}"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Update ${MODULE_NAME} to version ${GITHUB_REF_NAME}"
          git push origin "$BRANCH_NAME"

      - name: Open Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"
          MODULE_NAME="${{ steps.extract_module.outputs.module_name }}"
          gh pr create --title "Update ${MODULE_NAME} to ${GITHUB_REF_NAME}" --body "Automated update of ${MODULE_NAME} module."
